---
title: "greta.Rmd"
author: "Carl Boettiger"
date: "5/30/2019"
output: html_document
---

```{r message = FALSE, warning=FALSE}
library(tidyverse)
library(greta) # remotes::install_github("greta-dev/greta")
```


```{r}
data <- read_csv("../data/reps.csv")
data %>% ggplot(aes(t,x, group=reps)) + geom_line(alpha=0.1)
```

```{r}
wide <- data %>% spread(reps, x) %>% select(-t) %>% select(1:3) %>% as.matrix()
n <- dim(wide)[1]

```


```{r}
x_t1 <- wide[-1,] # data$x[-1]
x_t <- wide[-n,] # data$x[-100]
dim(x_t)
dim(x_t1)
#tibble(x_t, x_t1) %>% ggplot(aes(x_t, x_t1)) + geom_point()
```

```{r}
r <- 0.05 
Q <- 5
#sigma <- 0.02
#a <- 0.0233
K <- uniform(0, 10)
H <- uniform(0,  2)
a <- uniform(0, 1)
#r <- uniform(0, 1)
#Q <- uniform(0, 10)
sigma <- uniform(0, 1)

# Model
mean <- x_t + r * x_t * (1 - x_t / K) - a * x_t ^ Q / (x_t ^ Q + H ^ Q)
distribution(x_t1) <- normal(mean, sigma)
m <- model(K, a, H, sigma)
```

```{r}
draws <- mcmc(m, n_samples = 1000, warmup = 1000, chains = 4)
```

```{r}
summary(draws)
```

```{r}
bayesplot::mcmc_trace(draws)
```



```{r}
```

