---
title: "greta.Rmd"
author: "Carl Boettiger"
date: "5/30/2019"
output: html_document
---

```{r}
library(tidyverse)
library(greta) # remotes::install_github("greta-dev/greta")
```

```{r}
x0 <- 0.2

# constants
n <- 500
r <- 0.05 
K <- 2 
sigma <- 0.02

x <- y <- numeric(n)
x[1] <- x0
dB <- rnorm(n, 0, sigma)
for(t in 1:(n-1)){
  y[t+1] <- x[t] + r * x[t] * (1 - x[t] / K) + dB[t]
  x[t+1] <- max(y[t+1], 0)
}
data <- data.frame(t = 1:n, x)

data %>% ggplot(aes(t,x)) + geom_line()
```

```{r}
x_t1 <- data$x[-1]
x_t <- data$x[-100]
tibble(x_t, x_t1) %>% ggplot(aes(x_t, x_t1)) + geom_point()
```

```{r}
# Priors
r <- uniform(0,1)
K <- uniform(0, 10)
sigma <- uniform(0, 1)
mean <- x_t + r * x_t * (1 - x_t / K)
distribution(x_t1) <- normal(mean, sigma)
m <- model(r, K, sigma)
```

```{r warning=FALSE}
draws <- mcmc(m, n_samples = 1000, warmup = 2000, chains = 4)
```

```{r}
summary(draws)
```

```{r}
samples <-  
  map_dfr(draws, 
          function(x) data.frame(x, t = 1:dim(x)[1]), 
          .id = "chain") %>% 
  gather(variable, value, -t, -chain)

samples %>%  
  ggplot(aes(t,value, col=chain, group=chain)) + 
  geom_line() +
  facet_wrap(~variable, scales = "free", ncol = 1) + 
  scale_color_viridis_d()
```


```{r}
bayesplot::mcmc_trace(draws)
```

```{r}
summary(draws)
```


```{r}
```

